---
title: "Team Fight Tactics Traits"
author: "Caleb Trujillo"
date: "2/1/2022"
output: html_document
---

```{r setup, include=FALSE}
if(!require(tidygraph))install.packages(tidygraph)
if(!require(tidyverse))install.packages(tidyverse)
if(!require(googledrive))install.packages(googledrive)
if(!require(readxl))install.packages(readxl)
if(!require(igraph))install.packages(igraph)
if(!require(ggraph))install.packages(ggraph)
if(!require("RColorBrewer"))install.packages("RColorBrewer")
if(!require("ggiraph"))install.packages("ggiraph")
```

## TFT champions and traits

The figure below displays champions and the relationships they have to various traits. Classes and origins are indicated.

```{r load data, include=False}
drive_download("https://docs.google.com/spreadsheets/d/1YcpAryA_AXxMxHq8DNIb6QjkoJjmBE-LxYlegOzpR94/edit#gid=1653168612", overwrite = TRUE)
nodes <- read_excel("TFT traits.xlsx", 
    sheet = "nodes", col_names = FALSE, col_types = c("text", 
        "text", "numeric"))
colnames(nodes) <- c("Node", "Type", "Cost")

edges <- read_excel("TFT traits.xlsx", 
    sheet = "Champion traits 6.5", col_names = FALSE, col_types = c("text", 
        "text", "text"))
colnames(edges) <- c("Trait", "Champion", "Type")
edges <- select(edges,!Type)
```
```{r network, include=False}
g <- graph_from_data_frame(edges, vertices = nodes) %>%
  #set_vertex_attr("Cost", value = nodes$Cost) %>%
  as_tbl_graph()

V(g)$shape <- recode(V(g)$Type, Champion = "Square", Origin = "Hex", Class = "Circle")

traits <- V(g)[V(g)$Type != "Champion"]
V(g)$color[V(g)$Type != "Champion"] <- rainbow(length(traits))

edge.start <- ends(g, es=E(g), names=F)[,1]
edge.col <- V(g)$color[edge.start]

graph <- g %>%
  ggraph(layout = 'kk') + 
  geom_edge_fan(aes(color = edge.col)) +
  geom_node_point(aes(size = Cost, color = V(g)$color, shape = shape),show.legend = FALSE) +
  #geom_node_text(aes(label = name,size = degree(greys)),
              #   family = "serif",repel = TRUE)+
 geom_node_label(aes(label = name, fill = V(g)$color), repel = TRUE) +
  theme_graph() +
  theme(legend.position = "none")

graph

ggraph(g, layout = "manual", x = x, y = y) + 
	 geom_edge_link0(edge_colour = "#A8A8A8",
    edge_width = 0.8, edge_alpha = 1, arrow = arrow(angle = 30, length = unit(0.15,
        "inches"), ends = "last", type = "closed")) + 
	 geom_node_point(aes(fill = color),
    colour = "#000000", size = 4, shape = 21, stroke = 0.3) + 
	 scale_fill_brewer(palette = "Set3",
    na.value = "gray53") + 
	 geom_node_text(aes(label = name), colour = "#000000",
    size = 2.5, family = "Helvetica", repel = TRUE, segment.alpha = 0) + 
    theme_graph() + 
	 theme(legend.position = "none")
```

Adding interactivity 

```{r graph, echo=FALSE}

girafe(ggobj = graph,width_svg = 5, height_svg = 5,
       options = list(opts_sizing(rescale = FALSE)))
```